### ISSUE TITLE
Plethora crashes when trying to type in neural connector

### ISSUE THREAD

**Issue by ParlocameonTheDev** [SquidDev-CC/ccjam-2016#173] opened 2018-12-31 00:09 UTC
Crash Report: 
```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  EnderCorePlugin (EnderCore-1.12.2-0.5.43.jar)
  TransformerLoader (OpenComputers-MC1.12.2-1.7.3.146.jar)
Contact their authors BEFORE contacting forge

// Who set us up the TNT?

Time: 12/30/18 5:32 PM
Description: Updating screen events

java.lang.NoSuchMethodError: dan200.computercraft.client.gui.widgets.WidgetTerminal.keyTyped(CI)V
	at org.squiddev.plethora.gameplay.client.gui.GuiNeuralInterface.func_73869_a(GuiNeuralInterface.java:85)
	at net.minecraft.client.gui.GuiScreen.func_146282_l(GuiScreen.java:558)
	at org.squiddev.plethora.gameplay.client.gui.GuiNeuralInterface.func_146282_l(GuiNeuralInterface.java:111)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:512)
	at org.squiddev.plethora.gameplay.client.gui.GuiNeuralInterface.func_146269_k(GuiNeuralInterface.java:58)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1759)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at org.squiddev.plethora.gameplay.client.gui.GuiNeuralInterface.func_73869_a(GuiNeuralInterface.java:85)
	at net.minecraft.client.gui.GuiScreen.func_146282_l(GuiScreen.java:558)
	at org.squiddev.plethora.gameplay.client.gui.GuiNeuralInterface.func_146282_l(GuiNeuralInterface.java:111)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:512)
	at org.squiddev.plethora.gameplay.client.gui.GuiNeuralInterface.func_146269_k(GuiNeuralInterface.java:58)

-- Affected screen --
Details:
	Screen name: org.squiddev.plethora.gameplay.client.gui.GuiNeuralInterface

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['Parlocameon'/8480107, l='MpServer', x=1021.73, y=67.88, z=-1165.26]]
	Chunk stats: MultiplayerChunkCache: 1368, 1368
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (143,64,-432), Chunk: (at 15,4,0 in 8,-27; contains blocks 128,0,-432 to 143,255,-417), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Level time: 1780874 game time, 550714 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 44 total; [EntityCow['Cow'/8480321, l='MpServer', x=1033.34, y=77.00, z=-1218.83], EntityCow['Cow'/8480385, l='MpServer', x=1083.64, y=72.00, z=-1205.83], EntityCow['Cow'/8480320, l='MpServer', x=1028.33, y=79.00, z=-1225.30], EntityCow['Cow'/8480384, l='MpServer', x=1063.43, y=66.00, z=-1166.76], EntityBat['Bat'/8480323, l='MpServer', x=1030.25, y=46.10, z=-1091.75], EntityCow['Cow'/8480387, l='MpServer', x=1082.70, y=72.00, z=-1206.36], EntityBat['Bat'/8480258, l='MpServer', x=955.58, y=19.10, z=-1231.75], EntityCow['Cow'/8480322, l='MpServer', x=1029.55, y=80.00, z=-1227.78], EntityCow['Cow'/8480386, l='MpServer', x=1074.52, y=74.00, z=-1207.77], EntityBat['Bat'/8480325, l='MpServer', x=1022.52, y=44.35, z=-1093.37], EntityCow['Cow'/8480389, l='MpServer', x=1070.50, y=65.00, z=-1168.18], EntityMinecartChest['Minecart with Chest'/8480324, l='MpServer', x=1016.50, y=44.06, z=-1091.50], EntityCow['Cow'/8480388, l='MpServer', x=1067.47, y=66.00, z=-1168.20], EntitySquid['Squid'/8480327, l='MpServer', x=1032.43, y=51.90, z=-1118.15], EntityCow['Cow'/8480391, l='MpServer', x=1077.52, y=72.00, z=-1193.23], EntityBat['Bat'/8480326, l='MpServer', x=1016.74, y=44.11, z=-1095.51], EntityCow['Cow'/8480390, l='MpServer', x=1087.20, y=73.00, z=-1189.51], EntitySquid['Squid'/8480328, l='MpServer', x=1012.16, y=59.25, z=-1126.99], EntityPlayerSP['Parlocameon'/8480107, l='MpServer', x=1021.73, y=67.88, z=-1165.26], EntityBat['Bat'/8480273, l='MpServer', x=968.75, y=46.10, z=-1147.42], EntityMinecartChest['Minecart with Chest'/8480277, l='MpServer', x=968.50, y=41.06, z=-1116.50], EntityBat['Bat'/8480341, l='MpServer', x=1019.15, y=16.10, z=-1238.77], EntityBat['Bat'/8480276, l='MpServer', x=962.77, y=13.10, z=-1092.68], EntityBat['Bat'/8480151, l='MpServer', x=1019.55, y=38.10, z=-1172.25], EntityMinecartChest['Minecart with Chest'/8480278, l='MpServer', x=974.50, y=43.06, z=-1131.50], EntityBat['Bat'/8480152, l='MpServer', x=1010.57, y=57.10, z=-1176.25], EntityCow['Cow'/8480344, l='MpServer', x=1044.81, y=80.00, z=-1243.68], EntityCow['Cow'/8480411, l='MpServer', x=1079.42, y=67.00, z=-1151.18], EntityCow['Cow'/8480413, l='MpServer', x=1089.45, y=70.00, z=-1203.71], EntityCow['Cow'/8480416, l='MpServer', x=1096.50, y=70.00, z=-1198.82], EntityCow['Cow'/8480420, l='MpServer', x=1097.85, y=70.00, z=-1219.53], EntityCow['Cow'/8480377, l='MpServer', x=1087.50, y=71.00, z=-1219.50], EntitySquid['Squid'/8480251, l='MpServer', x=980.60, y=56.76, z=-1145.29], EntityCow['Cow'/8480379, l='MpServer', x=1084.47, y=68.00, z=-1229.15], EntityCow['Cow'/8480378, l='MpServer', x=1087.50, y=71.00, z=-1218.50], EntityBat['Bat'/8480317, l='MpServer', x=1018.16, y=16.82, z=-1183.60], EntityCow['Cow'/8480381, l='MpServer', x=1076.65, y=70.00, z=-1235.55], EntitySquid['Squid'/8480252, l='MpServer', x=982.23, y=56.90, z=-1135.88], EntitySquid['Squid'/8480316, l='MpServer', x=1005.45, y=59.50, z=-1150.45], EntityCow['Cow'/8480380, l='MpServer', x=1063.85, y=79.00, z=-1200.29], EntityCow['Cow'/8480319, l='MpServer', x=1026.50, y=79.00, z=-1225.50], EntityCow['Cow'/8480383, l='MpServer', x=1067.55, y=72.00, z=-1234.84], EntityBat['Bat'/8480318, l='MpServer', x=1010.52, y=53.10, z=-1193.75], EntityCow['Cow'/8480382, l='MpServer', x=1086.16, y=70.00, z=-1237.49]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:420)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2741)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:419)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 6762004712 bytes (6448 MB) / 9663676416 bytes (9216 MB) up to 9663676416 bytes (9216 MB)
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms9G -Xmx9G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M
	IntCache: cache: 0, tcache: 0, allocated: 15, tallocated: 95
	FML: MCP 9.42 Powered by Forge 14.23.5.2796 59 mods loaded, 59 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                                | Version           | Source                                          | Signature                                |
	|:------ |:--------------------------------- |:----------------- |:----------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft                         | 1.12.2            | minecraft.jar                                   | None                                     |
	| LCHIJA | mcp                               | 9.42              | minecraft.jar                                   | None                                     |
	| LCHIJA | FML                               | 8.0.99.99         | forge-1.12.2-14.23.5.2796.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge                             | 14.23.5.2796      | forge-1.12.2-14.23.5.2796.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | opencomputers|core                | 1.7.3.146         | minecraft.jar                                   | None                                     |
	| LCHIJA | securitycraft                     | v1.8.10           | [1.12.2]+SecurityCraft+v1.8.10.jar              | None                                     |
	| LCHIJA | appliedenergistics2               | rv6-stable-6      | appliedenergistics2-rv6-stable-6.jar            | dfa4d3ac143316c6f32aa1a1beda1e34d42132e5 |
	| LCHIJA | betterbuilderswands               | 0.12.0            | BetterBuildersWands-1.12-0.12.0.251+d6c4d93.jar | None                                     |
	| LCHIJA | biomesoplenty                     | 7.0.1.2422        | BiomesOPlenty-1.12.2-7.0.1.2422-universal.jar   | None                                     |
	| LCHIJA | buildcraftlib                     | 7.99.20           | buildcraft-all-7.99.20.jar                      | None                                     |
	| LCHIJA | buildcraftcore                    | 7.99.20           | buildcraft-all-7.99.20.jar                      | None                                     |
	| LCHIJA | buildcraftbuilders                | 7.99.20           | buildcraft-all-7.99.20.jar                      | None                                     |
	| LCHIJA | buildcrafttransport               | 7.99.20           | buildcraft-all-7.99.20.jar                      | None                                     |
	| LCHIJA | buildcraftsilicon                 | 7.99.20           | buildcraft-all-7.99.20.jar                      | None                                     |
	| LCHIJA | buildcraftcompat                  | 7.99.20           | buildcraft-all-7.99.20.jar                      | None                                     |
	| LCHIJA | buildcraftenergy                  | 7.99.20           | buildcraft-all-7.99.20.jar                      | None                                     |
	| LCHIJA | buildcraftfactory                 | 7.99.20           | buildcraft-all-7.99.20.jar                      | None                                     |
	| LCHIJA | buildcraftrobotics                | 7.99.20           | buildcraft-all-7.99.20.jar                      | None                                     |
	| LCHIJA | computercraft                     | 1.80pr1.12        | cc-tweaked-1.80pr1.12.jar                       | None                                     |
	| LCHIJA | cdm                               | 0.4.1             | cdm-0.4.1-mc1.12.2.jar                          | None                                     |
	| LCHIJA | cfm                               | 6.2.0             | cfm-6.2.0-mc1.12.2.jar                          | None                                     |
	| LCHIJA | codechickenlib                    | 3.2.2.353         | CodeChickenLib-1.12.2-3.2.2.353-universal.jar   | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | redstoneflux                      | 2.1.0             | RedstoneFlux-1.12-2.1.0.6-universal.jar         | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCHIJA | cofhcore                          | 4.6.1             | CoFHCore-1.12.2-4.6.1.22-universal.jar          | None                                     |
	| LCHIJA | cofhworld                         | 1.3.0             | CoFHWorld-1.12.2-1.3.0.6-universal.jar          | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCHIJA | asielib                           | 1.0.0             | Computronics-1.12.1-1.6.5.jar                   | None                                     |
	| LCHIJA | opencomputers                     | 1.7.3.146         | OpenComputers-MC1.12.2-1.7.3.146.jar            | None                                     |
	| LCHIJA | computronics                      | 1.6.5             | Computronics-1.12.1-1.6.5.jar                   | None                                     |
	| LCHIJA | endercore                         | 1.12.2-0.5.43     | EnderCore-1.12.2-0.5.43.jar                     | None                                     |
	| LCHIJA | jei                               | 4.13.1.225        | jei_1.12.2-4.13.1.225.jar                       | None                                     |
	| LCHIJA | thermalfoundation                 | 2.6.1             | ThermalFoundation-1.12.2-2.6.1.22-universal.jar | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCHIJA | thermalexpansion                  | 5.5.2             | ThermalExpansion-1.12.2-5.5.2.39-universal.jar  | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCHIJA | enderio                           | 5.0.39            | EnderIO-1.12.2-5.0.39.jar                       | None                                     |
	| LCHIJA | enderiointegrationtic             | 5.0.39            | EnderIO-1.12.2-5.0.39.jar                       | None                                     |
	| LCHIJA | enderiobase                       | 5.0.39            | EnderIO-1.12.2-5.0.39.jar                       | None                                     |
	| LCHIJA | enderioconduits                   | 5.0.39            | EnderIO-1.12.2-5.0.39.jar                       | None                                     |
	| LCHIJA | enderioconduitsappliedenergistics | 5.0.39            | EnderIO-1.12.2-5.0.39.jar                       | None                                     |
	| LCHIJA | enderioconduitsopencomputers      | 5.0.39            | EnderIO-1.12.2-5.0.39.jar                       | None                                     |
	| LCHIJA | enderioconduitsrefinedstorage     | 5.0.39            | EnderIO-1.12.2-5.0.39.jar                       | None                                     |
	| LCHIJA | enderiointegrationforestry        | 5.0.39            | EnderIO-1.12.2-5.0.39.jar                       | None                                     |
	| LCHIJA | enderiointegrationticlate         | 5.0.39            | EnderIO-1.12.2-5.0.39.jar                       | None                                     |
	| LCHIJA | enderiomachines                   | 5.0.39            | EnderIO-1.12.2-5.0.39.jar                       | None                                     |
	| LCHIJA | enderiopowertools                 | 5.0.39            | EnderIO-1.12.2-5.0.39.jar                       | None                                     |
	| LCHIJA | extrautils2                       | 1.0               | extrautils2-1.12-1.9.8.jar                      | None                                     |
	| LCHIJA | zerocore                          | 1.12-0.1.2.3      | zerocore-1.12-0.1.2.3.jar                       | None                                     |
	| LCHIJA | bigreactors                       | 1.12.2-0.4.5.50   | ExtremeReactors-1.12.2-0.4.5.50.jar             | None                                     |
	| LCHIJA | ic2                               | 2.8.105-ex112     | industrialcraft-2-2.8.105-ex112.jar             | de041f9f6187debbc77034a344134053277aa3b0 |
	| LCHIJA | ironchest                         | 1.12.2-7.0.54.838 | ironchest-1.12.2-7.0.54.838.jar                 | None                                     |
	| LCHIJA | mcjtylib_ng                       | 3.0.7             | mcjtylib-1.12-3.0.7.jar                         | None                                     |
	| LCHIJA | plethora-core                     | 1.1.13            | plethora-1.12.2-1.1.13.jar                      | None                                     |
	| LCHIJA | plethora                          | 1.1.13            | plethora-1.12.2-1.1.13.jar                      | None                                     |
	| LCHIJA | projecte                          | 1.12-PE1.3.2h     | ProjectE-1.12-PE1.3.2h.jar                      | None                                     |
	| LCHIJA | rftools                           | 7.59              | rftools-1.12-7.59.jar                           | None                                     |
	| LCHIJA | rftoolscontrol                    | 1.9.2             | rftoolsctrl-1.12-1.9.2.jar                      | None                                     |
	| LCHIJA | rftoolsdim                        | 5.63              | rftoolsdim-1.12-5.63.jar                        | None                                     |
	| LCHIJA | sgcraft                           | 1.13.2            | SGCraft-1.15.6-forge-release.jar                | None                                     |
	| LCHIJA | thermaldynamics                   | 2.5.3             | ThermalDynamics-1.12.2-2.5.3.16-universal.jar   | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCHIJA | simplyjetpacks                    | 2.2.10.63         | SimplyJetpacks2-1.12.2-2.2.10.63.jar            | None                                     |
	| LCHIJA | waystones                         | 4.0.67            | Waystones_1.12.2-4.0.67.jar                     | None                                     |

	Loaded coremods (and transformers): 
EnderCorePlugin (EnderCore-1.12.2-0.5.43.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
  com.enderio.core.common.transform.SimpleMixinPatcher
TransformerLoader (OpenComputers-MC1.12.2-1.7.3.146.jar)
  li.cil.oc.common.asm.ClassTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 417.35' Renderer: 'GeForce GTX 1080 Ti/PCIe/SSE2'
	AE2 Version: stable rv6-stable-6 for Forge 14.23.5.2768
	Ender IO: No known problems detected.

	!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
	!!!You are looking at the diagnostics information, not at the crash.       !!!
	!!!Scroll up until you see the line with '---- Minecraft Crash Report ----'!!!
	!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

	AE2 Integration: IC2:ON, RC:OFF, MFR:OFF, Waila:OFF, InvTweaks:OFF, JEI:ON, Mekanism:OFF, OpenComputers:ON, THE_ONE_PROBE:OFF, TESLA:OFF, CRAFTTWEAKER:OFF
	Launched Version: 1.12.2-forge1.12.2-14.23.5.2796
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 1080 Ti/PCIe/SSE2 GL version 4.6.0 NVIDIA 417.35, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 12x Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz
```

When attempting to open a neural interface with both a keyboard or a neural connector, Plethora causes my client to crash. I have tried this multiple times, and it always crashes. I am using CC: Tweaked in the place of ComputerCraft, but I don't think this would be a problem as I know the creator of Plethora is also the creator of CC: Tweaked.

**Mod Versions:**
CC: Tweaked: 1.80pr1.12
Computronics: 1.6.5
Plethora: 1.1.13

**Comment by SquidDev** [comment] 2018-12-31 09:10
Duplicate of SquidDev-CC/CC-Tweaked#87. I've been doing a bit of a refactor to CC:T, and managed to break Plethora. 

I'm planning to release today or tomorrow, but [this](https://www.dropbox.com/s/oxsz2b5czutcu9i/cc-tweaked-1.80pr1.12.jar?dl=1) should work for the time-being.

**Closed as completed** 2018-12-31 09:10 UTC
Labels: bug, duplicate

**Comment by ParlocameonTheDev** [comment] 2018-12-31 17:24
Thank you!
