### ISSUE TITLE
Thut Wearable Integration 

### ISSUE THREAD

**Issue by freakone20** [SquidDev-CC/ccjam-2016#132] opened 2018-07-27 04:37 UTC
Got crash when using plethora and thut Wearable, i think it's compatibility issues with thut Wearable mod

https://pastebin.com/BQW4ZJRz

plethora 1.12.2 1.1. 11
forge 2705

**Comment by SquidDev** [comment] 2018-07-27 06:05
Duplicate of #97. Sorry, I'll try to get an actual release out today for this.

**Closed as completed by SquidDev** 2018-07-27 06:05 UTC
Labels: bug, duplicate

**Comment by freakone20** [comment] 2018-07-27 07:59
didn't check that out, srry
